### ISSUE TITLE
Breaks the bookmark sidebar In currently Nightly

### ISSUE THREAD

**Issue by MikkCZ** [gomita/flatbm#4]
In current Nightly 53.0a1 when this extension is enabled, the bookmarks sidebar is empty (completely white) and no bookmarks or other elements are show.

**Comment by harl** [comment]
I can confirm that this happens exactly as described by @MikkCZ and that it is related to Flat Bookmarks in combination with the recent Nightly 53 versions. (It does not happen with Firefox/Waterfox 50.0.x)

**Comment by MikkCZ** [comment]
@gomita Are you still working on your add-ons development?

**Comment by MikkCZ** [comment]
Works in 1.13 again.
